### ISSUE TITLE
Tail doesn't reset when shorter route used

### ISSUE THREAD

**Issue by akc42** [PolymerElements/app-route#123] opened 2016-06-30 14:58 UTC
### Description

When nesting app-routes using tail from one route to feed the route of the next, the tail of the route doesn't reset when the path is such that the tail should be null

### Expected outcome

The tail should reset to path="" when no path is represented

### Actual outcome

The tail is left at whatever it was set at before

### Live Demo

https://jsbin.com/gosobuj/edit?html,output

(In my actual case, the various app-routes are embedded inside other elements with iron-page selections based on the /:page data.page values) and the other parameters in the example used for other types of selection.

### Steps to reproduce

With live demo above, start up and click on the various buttons.  Once set, tail2 doesn't seem responsive after shorter urls are in use.

### Browsers Affected

Not checked other than chrome, but this is probably not a browser issue.

**Comment by TimvdLippe** [comment] 2016-06-30 15:04
I think this is a duplicate of #75 which has been merged into #37

**Comment by rictic** [comment] 2016-07-14 19:39
As Tim said. Currently this is a deliberate decision not to update inactive app-route objects so that we don't thrash the dom of invisible elements. This gets us performance at the cost of correctness/unexpectedness. It's a tradeoff we're still actively considering.

At present the intent is that you watch the `active` boolean property on an app-route to react when an app-route no longer matches.

**Closed by rictic** 2016-07-14 19:39 UTC

**Comment by akc42** [comment] 2016-07-14 22:14
Now I understand all this better I am fine with this, EXCEPT #109 is a problem.  I put an observer directly on the bound active property on my surrounding element and it doesn't fire when going to true.
